resource_group_name = "AKS_cluster"
location            = "East US"
cluster_name        = "srinicluster"
kubernetes_version  = "1.23.12"
system_node_count   = 2
acr_name            = "sriniact"
client_id = 
client_secret=
tenant_id=
subscription_id=
