apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki-db
  namespace: mediawiki
spec:
  selector:
    matchLabels:
      app: mediawiki-db
  replicas: 1
  template:
    metadata:
      labels:
        app: mediawiki-db
    spec:
      containers:
        - name: mediawiki-db-container
          image: mariadb
          env:
            - name: MYSQL_DATABASE
              value: my_wiki
            - name: MARIADB_USER
              value: wikiuser
            - name: MARIADB_PASSWORD
              valueFrom:
               secretKeyRef:
                key: PASSWORD
                name: dbpasswd
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
               secretKeyRef:
                key: PASSWORD
                name: rootpasswd
          volumeMounts:
            - name: mariadb-vol
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-vol

---
apiVersion: v1
kind: Secret
metadata:
  name: rootpasswd
  namespace: mediawiki
type: Opaque
data:
  PASSWORD: bXktc2VjcmV0LXB3
---
apiVersion: v1
kind: Secret
metadata:
  name: dbpasswd
  namespace: mediawiki
type: Opaque
data:
  PASSWORD: bXlfY29vbF9zZWNyZXQ=


---
apiVersion: v1
kind: Service
metadata:
  name: mediawiki-db-srv
  namespace: mediawiki
  labels:
    app: mediawiki-db
spec:
  type: NodePort
  ports:
    - port: 3306
      protocol: TCP
  selector:
    app: mediawiki-db